[package]
edition = "2021"
name = "estudos_slint"
version = "0.1.0"

[dependencies]
slint = {version = "1.14", features = [
  "std",
  "backend-winit",
  "renderer-winit-skia", # ou "renderer-winit-femtovg" se preferir CPU
]}
[build-dependencies]
slint-build = "^1.14"
